baseURL = "https://foo.awsworkshops.io"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "AWS foo Workshop"
theme = "material"
uglyurls = true
sectionPagesMenu = "main"
pygmentsCodeFences = true
pygmentsStyle = "monokai"

[params]
editURL = "https://github.com/samdengler/aws-workshop-sample/edit/master/website/content/"
showVisitedLinks = false
description = "AWS foo Workshop"
disableSearch = true
disableAssetsBusting = true
disableLanguageSwitchingButton = true
disableShortcutsTitle = true

[outputs]
home = [ "HTML", "AMP", "RSS", "JSON"]
page = [ "HTML", "AMP"]

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
